### ISSUE TITLE
Cucumber reports do not get generated when scenarios fail

### ISSUE THREAD

**Issue by arjunvk** [masterthought/cucumber-reporting#113]
Hi,

I am able to successfully generate maven-cucumber reports when all my scenarios (across features) pass.

But the same reports don't get generated when some of the scenarios fail. I can see the JSON file gets generated successfully but for some reason the reporting plugin does not get invoked if a scenario fails.

The report log is as follows:

$ mvn install
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Quick Start Archetype 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.googlecode.totallylazy:totallylazy:jar:1.20 is missing, no dependency information available
[WARNING] The artifact junit:junit-dep:jar:4.11 has been relocated to junit:junit:jar:4.11
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ Automation_ERS_MVN ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\AVK\Project_WS\Automation_ERS_MVN\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ Automation_ERS_MVN ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ Automation_ERS_MVN ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\AVK\Project_WS\Automation_ERS_MVN\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ Automation_ERS_MVN ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ Automation_ERS_MVN ---
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ Automation_ERS_MVN ---
[INFO]
[INFO] --- maven-failsafe-plugin:2.11:integration-test (default) @ Automation_ERS_MVN ---
[INFO] Failsafe report directory: C:\AVK\Project_WS\Automation_ERS_MVN\target\failsafe-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running definition.CucumberRunner
Feature: View_Reports_submitted_by_Clients

  @View_Report
  Scenario Outline: Officer_Can_View_ERS_Reports_On_Console                 # src/test/java/features/reports_Submitted_By_Clients.feature:4
    Given The officer <Stub Officer Name> has logged into the ERS console
    When The officer <Officer Name> selects a client <Client Name>
    And Clicks on ERS Client report <Report Number>
    Then The bottom half of the screen should display the basic information

    Examples:
Started InternetExplorerDriver server (32-bit)
2.44.0.0
Listening on port 44072
HTML report initialised
ERS Stub page has been displayed;PASS
'Mike Acosta' has been selected on application;PASS
Launch ERS Console is present and clicked;PASS
View Reports Submitted by Clients is present and clicked;PASS
'Acosta, Mike' has been selected on List box 'Officer';PASS
'Clyburn, Earl' has been selected on List box 'Client';PASS
Report number 234 is invalid;FAIL
HTML report completed

  @View_Report
  Scenario Outline: Officer_Can_View_ERS_Reports_On_Console                 # src/test/java/features/reports_Submitted_By_Clients.feature:12
    Given The officer "Mike Acosta" has logged into the ERS console         # setup_And_TearDown.loginIntoERS(String)
    When The officer "Acosta, Mike" selects a client "Clyburn, Earl"        # reports_Submitted_By_Clients.officerSelectsClient(String,String)
    And Clicks on ERS Client report 234                                     # reports_Submitted_By_Clients.selectReport(int)
      java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at reportFramework.Report.updateLog(Report.java:211)
        at pages.ERS_View_Reports_Submitted_By_Clients.selectReport(ERS_View_Reports_Submitted_By_Clients.java:106)
        at definition.reports_Submitted_By_Clients.selectReport(reports_Submitted_By_Clients.java:38)
        at ?.And Clicks on ERS Client report 234(src/test/java/features/reports_Submitted_By_Clients.feature:7)

    Then The bottom half of the screen should display the basic information # reports_Submitted_By_Clients.verifySummaryReportFields()

1 Scenarios (1 failed)
4 Steps (1 failed, 1 skipped, 2 passed)
1m7.958s

java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at reportFramework.Report.updateLog(Report.java:211)
        at pages.ERS_View_Reports_Submitted_By_Clients.selectReport(ERS_View_Reports_Submitted_By_Clients.java:106)
        at definition.reports_Submitted_By_Clients.selectReport(reports_Submitted_By_Clients.java:38)
        at ?.And Clicks on ERS Client report 234(src/test/java/features/reports_Submitted_By_Clients.feature:7)

Tests run: 5, Failures: 2, Errors: 0, Skipped: 1, Time elapsed: 69.207 sec <<< FAILURE!

Results :

Failed tests:   And Clicks on ERS Client report 234(| \"Mike Acosta\" | \"Acosta\u002C Mike\" | \"Clyburn\u002C Earl\" | 234 |)
  | \"Mike Acosta\" | \"Acosta\u002C Mike\" | \"Clyburn\u002C Earl\" | 234 |

Tests run: 5, Failures: 2, Errors: 0, Skipped: 1

[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
[INFO]
[INFO] --- maven-failsafe-plugin:2.11:verify (default) @ Automation_ERS_MVN ---
[INFO] Failsafe report directory: C:\AVK\Project_WS\Automation_ERS_MVN\target\failsafe-reports
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:13 min
[INFO] Finished at: 2015-06-22T10:45:44-04:00
[INFO] Final Memory: 14M/223M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.11:verify (default) on project Automation_ERS_MVN: There are test failures.
[ERROR]
[ERROR] Please refer to C:\AVK\Project_WS\Automation_ERS_MVN\target\failsafe-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

When all scenarios PASS, I get the following log:

$ mvn install
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Maven Quick Start Archetype 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.googlecode.totallylazy:totallylazy:jar:1.20 is missing, no dependency information available
[WARNING] The artifact junit:junit-dep:jar:4.11 has been relocated to junit:junit:jar:4.11
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ Automation_ERS_MVN ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\AVK\Project_WS\Automation_ERS_MVN\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ Automation_ERS_MVN ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ Automation_ERS_MVN ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\AVK\Project_WS\Automation_ERS_MVN\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ Automation_ERS_MVN ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ Automation_ERS_MVN ---
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ Automation_ERS_MVN ---
[INFO] Building jar: C:\AVK\Project_WS\Automation_ERS_MVN\target\Automation_ERS_MVN-0.0.1-SNAPSHOT.jar
[INFO]
[INFO] --- maven-failsafe-plugin:2.11:integration-test (default) @ Automation_ERS_MVN ---
[INFO] Failsafe report directory: C:\AVK\Project_WS\Automation_ERS_MVN\target\failsafe-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running definition.CucumberRunner
Feature: View_Reports_submitted_by_Clients

  @View_Report
  Scenario Outline: Officer_Can_View_ERS_Reports_On_Console                 # src/test/java/features/reports_Submitted_By_Clients.feature:4
    Given The officer <Stub Officer Name> has logged into the ERS console
    When The officer <Officer Name> selects a client <Client Name>
    And Clicks on ERS Client report <Report Number>
    Then The bottom half of the screen should display the basic information

    Examples:
Started InternetExplorerDriver server (32-bit)
2.44.0.0
Listening on port 44038
HTML report initialised
ERS Stub page has been displayed;PASS
'Mike Acosta' has been selected on application;PASS
Launch ERS Console is present and clicked;PASS
View Reports Submitted by Clients is present and clicked;PASS
'Acosta, Mike' has been selected on List box 'Officer';PASS
'Clyburn, Earl' has been selected on List box 'Client';PASS
Report number '2' is present and clicked;PASS
'Report for:' is present as expected.;PASS
'Report Date:' is present as expected.;PASS
'Client ID:' is present as expected.;PASS
'PACTS Type:' is present as expected.;PASS
'Question Set:' is present as expected.;PASS
'Method:' is present as expected.;PASS
'Status:' is present as expected.;PASS
'Location:' is present as expected.;PASS
'Chronos:' is present as expected.;PASS
HTML report completed

  @View_Report
  Scenario Outline: Officer_Can_View_ERS_Reports_On_Console                 # src/test/java/features/reports_Submitted_By_Clients.feature:12
    Given The officer "Mike Acosta" has logged into the ERS console         # setup_And_TearDown.loginIntoERS(String)
    When The officer "Acosta, Mike" selects a client "Clyburn, Earl"        # reports_Submitted_By_Clients.officerSelectsClient(String,String)
    And Clicks on ERS Client report 2                                       # reports_Submitted_By_Clients.selectReport(int)
    Then The bottom half of the screen should display the basic information # reports_Submitted_By_Clients.verifySummaryReportFields()

1 Scenarios (1 passed)
4 Steps (4 passed)
1m26.202s

Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 87.534 sec

Results :

Tests run: 5, Failures: 0, Errors: 0, Skipped: 0

[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
[INFO]
[INFO] --- maven-failsafe-plugin:2.11:verify (default) @ Automation_ERS_MVN ---
[INFO] Failsafe report directory: C:\AVK\Project_WS\Automation_ERS_MVN\target\failsafe-reports
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
[INFO]
[INFO] --- maven-cucumber-reporting:0.0.7:generate (execution) @ Automation_ERS_MVN ---
[INFO] About to generate Cucumber report.
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ Automation_ERS_MVN ---
[INFO] Installing C:\AVK\Project_WS\Automation_ERS_MVN\target\Automation_ERS_MVN-0.0.1-SNAPSHOT.jar to C:\Users\vijayakumara\.m2\repository\ao\uscourts\Automation_ERS_MVN\0.0.1-SNAPSHOT\Automation_ERS_MVN-0.0.1-SNAPSHOT.jar
[INFO] Installing C:\AVK\Project_WS\Automation_ERS_MVN\pom.xml to C:\Users\vijayakumara\.m2\repository\ao\uscourts\Automation_ERS_MVN\0.0.1-SNAPSHOT\Automation_ERS_MVN-0.0.1-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:32 min
[INFO] Finished at: 2015-06-22T10:42:40-04:00
[INFO] Final Memory: 14M/152M
[INFO] ------------------------------------------------------------------------

My POM file is as follows:

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  
  <groupId>ao.uscourts</groupId>
  <artifactId>Automation_ERS_MVN</artifactId>
  <packaging>jar</packaging>
  <version>0.0.1-SNAPSHOT</version>
  
  <name>Maven Quick Start Archetype</name>
  <url>http://maven.apache.org</url>
  
  <dependencies>
  		<dependency>
  			<groupId>org.seleniumhq.selenium</groupId>
           		<artifactId>selenium-server</artifactId>
    			<version>2.45.0</version>
    	</dependency>
  		<dependency>
     		<groupId>info.cukes</groupId>
      		<artifactId>cucumber-java</artifactId>
      		<version>1.2.2</version>
      		</dependency>
        <dependency>
            <groupId>info.cukes</groupId>
            <artifactId>cucumber-junit</artifactId>
            <version>1.2.2</version>
        </dependency>
        <dependency>
    		<groupId>info.cukes</groupId>
    		<artifactId>cucumber-picocontainer</artifactId>
    		<version>1.2.2</version>
		</dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit-dep</artifactId>
            <version>4.11</version>
        </dependency>
        <dependency>
    		<groupId>com.microsoft.sqlserver</groupId>
    		<artifactId>sqljdbc4</artifactId>
    		<version>4.1</version>
		</dependency>
		<dependency>
        	<groupId>com.ibm.informix</groupId>
            <artifactId>ifxjdbc</artifactId>
            <version>1.0</version>
		</dependency>
		<dependency>
        	<groupId>ao.AVK</groupId>
  			<artifactId>common</artifactId>
  			<version>0.0.1-SNAPSHOT</version>
		</dependency>
		<dependency>
           <groupId>com.googlecode.totallylazy</groupId>
           <artifactId>totallylazy</artifactId>
           <version>1.20</version>
   		</dependency>
		
		
    	
  </dependencies>
  <build>
		<plugins>
        	<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.2</version>
                <configuration>
                    <source>1.6</source>
                    <target>1.6</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.18.1</version>
                <dependencies>
                	<dependency>
    					<groupId>org.apache.maven.surefire</groupId>
					    <artifactId>surefire-junit47</artifactId>
    					<version>2.18.1</version>
					</dependency>
            	</dependencies>
            </plugin>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.11</version>
                <configuration>
                    <includes>
                        <include>**/*Test.java</include>
                        <include>**/Test*.java</include>
                        <include>**/When*.java</include>
                        <include>**/*Runner.java</include>
                    </includes>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>net.masterthought</groupId>
                <artifactId>maven-cucumber-reporting</artifactId>
                <version>0.0.7</version>
                <executions>
                    <execution>
                        <id>execution</id>
                        <phase>verify</phase>
                        <goals>
                        	
                            
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <projectName>ERSAutomation</projectName>
                            <outputDirectory>${project.build.directory}/cucumber-html-reports</outputDirectory>
                            <cucumberOutput>${project.build.directory}/json/json-report.json</cucumberOutput>
                            <enableFlashCharts>true</enableFlashCharts>
                        </configuration>
                    </execution>
                </executions>
            </plugin> 
        </plugins>
    </build>
</project>

Can you help me solve this issue as it has been lingering for quite sometime now?

Regards,
Arjun

**Comment by arjunvk** [comment]
Hi,

Looks like I jumped the gun.

I fixed the issue by modifying the configuration parameter for 'surefire' plugin.

I added the following line and it works now:

<testFailureIgnore>true</testFailureIgnore>

Regards,
Arjun

**Comment by ajrodgar** [comment]
I have the same problem, please could you detail the solution? My plugin version is 0.1.0

**Comment by damianszczepanik** [comment]
Upgrade plugin

**Comment by mzanwar** [comment]
This problem seems to still be present as I have the same problem. The report does not generate when a test fails. However, it works fine when all the tests pass successfully. Maybe it has something to do with surefire plugin.... hmm

**Comment by fineashes** [comment]
You should add
<testFailureIgnore>true</testFailureIgnore>
in your configurations.
Here is the pom.xml
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.19.1</version>
                <configuration>
                	<testFailureIgnore>true</testFailureIgnore>
                    <excludes>
                        <exclude>none</exclude>
                    </excludes>
                    <includes>
                        
                        <include>**/*CucumberTest.java</include>
                    </includes>
                </configuration>

**Comment by shohilbagdai** [comment]
I have added this to pom.xml
< groupId>org.apache.maven.plugins< /groupId>
< artifactId>maven-surefire-plugin< /artifactId>
< version>2.19.1< /version>
< configuration >
< testFailureIgnore>true< /testFailureIgnore>

and its generating report now but just found out something that its giving me buils uccess notification even after scenario fails


Tests run: 29, Failures: 2, Errors: 0, Skipped: 0

[ERROR] There are test failures.

Please refer to C:\Users\******************\admin\target\surefire-reports for the individual test results.
[INFO] 
[INFO] --- maven-cucumber-reporting:3.7.0:generate (execution) @ admin ---
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
[INFO] About to generate Cucumber report.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:31 min
[INFO] Finished at: 2017-05-25T14:42:20+01:00
[INFO] Final Memory: 40M/621M
[INFO] ------------------------------------------------------------------------


does any one face same issue?
has anyone know the sollution?

**Comment by kprpalash82** [comment]
Hi, Did anyone found a solution for these. Currently i am also facing the same issue where if a test case has failed the report is not generated and if i add < testFailureIgnore>true< /testFailureIgnore> to Surefire it generates report but build is also success.

**Comment by laxersaz** [comment]
Yes we have a solution. We use testFailureIgnore, let cucumber-reporting build the report and finally use a simple custom built Maven fail rule that passes or fails the build based on the failsafe summary report.

**Comment by kprpalash82** [comment]
Thanks @laxersaz. Can you guide me how to have a custom Maven fail rule that passes or fails the build based on the failsafe summary report?

**Comment by laxersaz** [comment]
It is pretty straightforward. Just use the Maven Enforcer API as explained here: https://maven.apache.org/enforcer/enforcer-api/writing-a-custom-rule.html

In your rule you can define any custom logic to pass or fail your build. In our case I parsed the failsafe report results.

**Comment by kprpalash82** [comment]
Thanks @laxersaz that worked like a charm. I really appreciate your help.

**Comment by laxersaz** [comment]
Grest! I'm glad it worked for you!

**Comment by saroy1** [comment]
Thanks @laxersaz for your great help, could you please help me how to parse the failsafe report results in my custom function. in which method of EnforcerRule implementation class I have to update the for that report parsing.

**Comment by laxersaz** [comment]
Hi @saroy1 I don't really get your question. The failsafe report is just a simple XML file which is easy to parse. There you see the passed and failed test count.
Just do it inside the `execute()` method and check if you had any failures. If yes, throw an `EnforcerRuleException` which automatically fails your build.

**Comment by shaileshrahinj** [comment]
adding <testFailureIgnore>true</testFailureIgnore>  in maven-surefire-plugin solved the issue 

example:
<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.22.0</version>
				<configuration>
					<parallel>methods</parallel>
					<useUnlimitedThreads>true</useUnlimitedThreads>
					<testFailureIgnore>true</testFailureIgnore>
				</configuration>
