### ISSUE TITLE
Permission to push my commit

### ISSUE THREAD

**Issue by ArishArbab** [masterthought/cucumber-reporting#121]
I wish to contribute to this plugin. Unfortunately, I do not have permission to push to this repository.
Could you please allow write access to it ?

**Comment by kingsleyh** [comment]
Hi

I don't allow write access I'm afraid. Please fork and send a pull request if you would like to contribute 

Thanks

--Kingsley

**Comment by ArishArbab** [comment]
Thanks-I made a commit.
